# Generated by Django 5.2.3 on 2025-07-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("batting_style", models.CharField(max_length=50)),
                ("bowling_style", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("runs_scored", models.IntegerField()),
                ("wickets_taken", models.IntegerField()),
            ],
        ),
    ]
