# Generated by Django 5.2.3 on 2025-07-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("b_name", models.CharField(max_length=100)),
                ("a_name", models.CharField(max_length=100)),
            ],
        ),
    ]
